Depotakip/Controllers/DepoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Depotakip.Models;
using Microsoft.AspNetCore.Authorization;

namespace Depotakip.Controllers
{
    public class DepoController : Controller
    {
        private readonly MarketDbContext _context;

        public DepoController(MarketDbContext context)
        {
            _context = context;
        }

        // GET: Depo
        [Authorize]
        public async Task<IActionResult> Index()
        {
              return _context.Depolar != null ? 
                          View(await _context.Depolar.ToListAsync()) :
                          Problem("Entity set 'MarketDbContext.Depolar'  is null.");
        }

        // GET: Depo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Depolar == null)
            {
                return NotFound();
            }

            var depo = await _context.Depolar
                .FirstOrDefaultAsync(m => m.DepoId == id);
            if (depo == null)
            {
                return NotFound();
            }

            return View(depo);
        }

        // GET: Depo/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DepoId,Ad,Adres,Kapasite,PersonelSayisi")] Depo depo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(depo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(depo);
        }

        // GET: Depo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Depolar == null)
            {
                return NotFound();
            }

            var depo = await _context.Depolar.FindAsync(id);
            if (depo == null)
            {
                return NotFound();
            }
            return View(depo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepoId,Ad,Adres,Kapasite,PersonelSayisi")] Depo depo)
        {
            if (id != depo.DepoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(depo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepoExists(depo.DepoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(depo);
        }

        // GET: Depo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Depolar == null)
            {
                return NotFound();
            }

            var depo = await _context.Depolar
                .FirstOrDefaultAsync(m => m.DepoId == id);
            if (depo == null)
            {
                return NotFound();
            }

            return View(depo);
        }

        // POST: Depo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Depolar == null)
            {
                return Problem("Entity set 'MarketDbContext.Depolar'  is null.");
            }
            var depo = await _context.Depolar.FindAsync(id);
            if (depo != null)
            {
                _context.Depolar.Remove(depo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepoExists(int id)
        {
          return (_context.Depolar?.Any(e => e.DepoId == id)).GetValueOrDefault();
        }
    }
}

Depotakip/Controllers/ReyonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Depotakip.Models;

namespace Depotakip.Controllers
{
    public class ReyonController : Controller
    {
        private readonly MarketDbContext _context;

        private readonly IWebHostEnvironment _hostEnvironment;

        public ReyonController(MarketDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Reyon
        public async Task<IActionResult> Index()
        {
            var marketContext = _context.Reyonlar.Include(r => r.Depo);
            return View(await marketContext.ToListAsync());
        }

        // GET: Reyon/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reyonlar == null)
            {
                return NotFound();
            }

            var reyon = await _context.Reyonlar
                .Include(r => r.Depo)
                .FirstOrDefaultAsync(m => m.ReyonId == id);
            if (reyon == null)
            {
                return NotFound();
            }

            return View(reyon);
        }

        // GET: Reyon/Create
        public IActionResult Create()
        {
            ViewData["DepoId"] = new SelectList(_context.Depolar, "DepoId", "Ad");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReyonId,ReyonAd,ImageFile,DepoId")] Reyon reyon)
        {

            //For Image
            string wwwrootpath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(reyon.ImageFile.FileName);  //parameter
            string extension = Path.GetExtension(reyon.ImageFile.FileName);
            reyon.ReyonImg = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;  //file name +time+extension
            string path = Path.Combine(wwwrootpath + "/Image/", fileName); // with rootpath rootpath+Image file (in the wwwroot ) and combine file name
            using (var filestream = new FileStream(path, FileMode.Create))
            {
                await reyon.ImageFile.CopyToAsync(filestream);

            }
            _context.Add(reyon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
          
            ViewData["DepoId"] = new SelectList(_context.Depolar, "DepoId", "DepoId", reyon.DepoId);
            return View(reyon);
        }

        // GET: Reyon/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Reyonlar == null)
            {
                return NotFound();
            }

            var reyon = await _context.Reyonlar.FindAsync(id);
            if (reyon == null)
            {
                return NotFound();
            }
            ViewData["DepoId"] = new SelectList(_context.Depolar, "DepoId", "Ad", reyon.DepoId);
            return View(reyon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReyonId,ReyonAd,ImageFile,DepoId")] Reyon reyon)
        {
            string wwwrootpath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(reyon.ImageFile.FileName); 
            string extension = Path.GetExtension(reyon.ImageFile.FileName);
            reyon.ReyonImg = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;  
            string path = Path.Combine(wwwrootpath + "/Image/", fileName); 
            using (var filestream = new FileStream(path, FileMode.Create))
            {
                await reyon.ImageFile.CopyToAsync(filestream);

            }


            if (id != reyon.ReyonId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reyon);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReyonExists(reyon.ReyonId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepoId"] = new SelectList(_context.Depolar, "DepoId", "DepoId", reyon.DepoId);
            return View(reyon);
        }

        // GET: Reyon/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Reyonlar == null)
            {
                return NotFound();
            }

            var reyon = await _context.Reyonlar
                .Include(r => r.Depo)
                .FirstOrDefaultAsync(m => m.ReyonId == id);
            if (reyon == null)
            {
                return NotFound();
            }

            return View(reyon);
        }

        // POST: Reyon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Reyonlar == null)
            {
                return Problem("Entity set 'MarketContext.Reyonlar'  is null.");
            }
            var reyon = await _context.Reyonlar.FindAsync(id);
            if (reyon != null)
            {
                _context.Reyonlar.Remove(reyon);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReyonExists(int id)
        {
            return (_context.Reyonlar?.Any(e => e.ReyonId == id)).GetValueOrDefault();
        }
    }
}

Depotakip/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Depotakip.Models;
using Microsoft.AspNetCore.Authorization;

namespace Depotakip.Controllers
{
    public class UrunController : Controller
    {
        private readonly MarketDbContext _context;

        private readonly IWebHostEnvironment _hostEnvironment;

        public UrunController(MarketDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment; 
        }

        // GET: Urun
       // [Authorize] 
        public async Task<IActionResult> Index()
        {
            var marketContext = _context.Urunler.Include(u => u.Kategori);
            return View(await marketContext.ToListAsync());
        }

        // GET: Urun/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Urunler == null)
            {
                return NotFound();
            }

            var urun = await _context.Urunler
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.UrunId == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        // GET: Urun/Create
        public IActionResult Create()
        {
            ViewData["KategoriId"] = new SelectList(_context.Kategoriler, "KategoriId", "KategoriAd");
            return View();
        }

        // POST: Urun/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UrunId,KategoriId,UrunAd,UrunAdet,UrunFiyat,Gelistarih,ImageFile")] Urun urun)
        {
            string wwwrootpath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(urun.ImageFile.FileName);  //parameter  aldık
            string extension = Path.GetExtension(urun.ImageFile.FileName);
            urun.UrunFoto = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;  //file name +time+extension
            string path = Path.Combine(wwwrootpath + "/Image/", fileName); // with rootpath rootpath+Image file (in the wwwroot ) and combine file name
            using (var filestream = new FileStream(path, FileMode.Create))
            {
                await urun.ImageFile.CopyToAsync(filestream);

            }
            //if (ModelState.IsValid)
            //{
            _context.Add(urun);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            //}
            ViewData["KategoriId"] = new SelectList(_context.Kategoriler, "KategoriId", "KategoriId", urun.KategoriId);
            return View(urun);
        }

        // GET: Urun/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Urunler == null)
            {
                return NotFound();
            }

            var urun = await _context.Urunler.FindAsync(id);
            if (urun == null)
            {
                return NotFound();
            }
            ViewData["KategoriId"] = new SelectList(_context.Kategoriler, "KategoriId", "KategoriAd", urun.KategoriId);
            return View(urun);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UrunId,KategoriId,UrunAd,UrunAdet,UrunFiyat,Gelistarih,ImageFile")] Urun urun)
        {
            string wwwrootpath = _hostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(urun.ImageFile.FileName); 
            string extension = Path.GetExtension(urun.ImageFile.FileName);
            urun.UrunFoto = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;  
            string path = Path.Combine(wwwrootpath + "/Image/", fileName); 
            using (var filestream = new FileStream(path, FileMode.Create))
            {
                await urun.ImageFile.CopyToAsync(filestream);

            }
            if (id != urun.UrunId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(urun);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UrunExists(urun.UrunId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KategoriId"] = new SelectList(_context.Kategoriler, "KategoriId", "KategoriId", urun.KategoriId);
            return View(urun);
        }

        // GET: Urun/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Urunler == null)
            {
                return NotFound();
            }

            var urun = await _context.Urunler
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.UrunId == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        // POST: Urun/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Urunler == null)
            {
                return Problem("Entity set 'MarketContext.Urunler'  is null.");
            }
            var urun = await _context.Urunler.FindAsync(id);
            if (urun != null)
            {
                _context.Urunler.Remove(urun);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UrunExists(int id)
        {
            return (_context.Urunler?.Any(e => e.UrunId == id)).GetValueOrDefault();
        }
    }
}

Depotakip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        
<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Sağlam Market</title>
   
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
     
    </head>
    <body>


        <!-- Navbar-->
              <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
               <a class="navbar-brand ps-3" href="/Urun/Index">SAĞLAM MARKET</a>
                    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
             <!--  Duzenlenecek -->
            </form>
            
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        
                        <li><hr class="dropdown-divider" /></li>
                       
                  
                    @Html.ActionLink("Çıkış","LogOut","Admin",null,new{@class="dropdown-item"})
                    
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
     
             <div  id="layoutSidenav_content">
                <main>
                  <div class="container-fluid px-4">
                        <h1 class="mt-4">KONTROL PANELİ</h1>
                        <ol class="breadcrumb mb-4">
                             <h3 class="mt-4">Hoşgeldin Admin</h3>
                        </ol>


                         <div class="row">
                            <div class="col-xl-4 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">Depolar</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                     
                                       @Html.ActionLink("Detayları Gör","Index","Depo",null,new{@class="small text-white stretched-link"})
                                       
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        
                            <div class="col-xl-4 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body"> Reyonlar</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        @Html.ActionLink("Detayları Gör","Index","Reyon",null,new{@class="small text-white stretched-link"})
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-4 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">Kategoriler</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        @Html.ActionLink("Detayları Gör","Index","Kategori",null,new{@class="small text-white stretched-link"})
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                          <div class="row">
                            <div class="col-xl-4 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">Tedarikçiler</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                     
                                       @Html.ActionLink("Detayları Gör","Index","Tedarikci",null,new{@class="small text-white stretched-link"})
                                       
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        
                            <div class="col-xl-4 col-md-6">
                                <div class="card bg-secondary text-white mb-4">
                                    <div class="card-body"> Personeller</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        @Html.ActionLink("Detayları Gör","Index","Personel",null,new{@class="small text-white stretched-link"})
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                             <div class="col-xl-4 col-md-6">
                                <div class="card bg-info text-white mb-4">
                                    <div class="card-body"> Ürünler</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        @Html.ActionLink("Detayları Gör","Index","Urun",null,new{@class="small text-white stretched-link"})
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                         
                        </div>
                        <div class="card mb-4">
                            <div class="card-body">
                                @RenderBody()
                            
                            </div>
                        </div>
                        <div style="height: 75vh"></div>
                      
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright 2023 - SağlamMarket</div>
               
                        </div>
                    </div>
                </footer>
            </div>
        </div>

 
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="assets/demo/chart-area-demo.js"></script>
        <script src="assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="js/datatables-simple-demo.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

Depotakip/Views/Shared/_LayoutLogin.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>

	<!-- Bootstrap-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<link rel="stylesheet"  href="~/newcss/style.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">

	 <!-- RenderBody-->
		@RenderBody()
</div>
</div>
</body>
</html>